version: '3.8'

services:
  clean-architecture:
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./src:/app/src
      - ./CleanArchitecture.WebAPI/appsettings.Development.json:/app/appsettings.Development.json